# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and https://github.com/craigcitro/r-travis/wiki
#
# I am adding bioc_packages to see if they are (hopefully) cached somewhere?
#
# Timing: Total time is 46 mins(!)
#
#   * ~ 6 minutes to get to the stage where we are building bioconductor
#   * ~ 20 minutes (1220 seconds) to build bioc and dependencies
#   * ~ 1.5 mins to build multiGSEA
#   * ~ 11 mins to run R CMD check
#
# packages
#
# Modeling this after the waldronlab/MultiAssayExperiment/.travis.yml
language: r
# r: bioc-devel
r: bioc-release
dist: trusty
sudo: required
cache: packages
warnings_are_errors: false


branches:
  only:
    - master
    - develop

r_binary_packages:
  - broom
  - checkmate
  - DBI
  - data.table
  - dbplyr
  - dplyr
  - glue
  - jsonlite
  - reshape2
  - RSQLite
  - yaml

# These r-cran-packages are not available for install, so they will be installed
# manually during the bioc installation.
#  - circlize
#  - GetoptLong
#  - GlobalOptions
#  - bookdown
#  - BioocManager
#  - Hmisc (depends on r-recommended and r-cran-nnet which won't be installed)
#  - htmlTable (depends on r-recommended)

bioc_packages:
  - edgeR
  - limma
  - rhdf5

r_github_packages:
  - lianos/multiGSEA

# after_success:
#   - Rscript -e 'library(covr); codecov()'
